language: go
go:
- '1.0'
- '1.3'

notifications:
    slack: umscloud:T4eDhcMM87W5U4iWTSWKfABP
    webhooks:
        - https://api.grouk.com/webhook/56432369e4b07d2ced36529e/e648d7a659e04d18aec9f1446e21f63d
